name: CD - Deploy Raspberry Pi Python Project

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - application/**

jobs:
  deploy:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: ./application

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      
      - name: Set build number
        id: build-number
        run: echo "BUILD_NUMBER=$(date '+%Y.%m.%d.%H.%M.%S')" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker buildx create --use
          docker buildx build \
            --tag ${{ vars.DOCKERHUB_USERNAME }}/raspberrypi-blinking-led:${{ env.BUILD_NUMBER }} \
#            --tag ${{ vars.DOCKERHUB_USERNAME }}/raspberrypi-blinking-led:latest \
            --file Dockerfile \
            --push .