name: CI - Build Raspberry Pi Python Project

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - ./application/**

jobs:
  build:
    runs-on: self-hosted

    defaults:
        run:
          working-directory: ./application

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: python3 -m unittest # Replace with your test command or script